/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as flickEnsSol from "./FlickENS.sol";
export type { flickEnsSol };
import type * as ierc721EnumerableSol from "./IERC721Enumerable.sol";
export type { ierc721EnumerableSol };
import type * as nftSol from "./NFT.sol";
export type { nftSol };
import type * as offchainResolverSol from "./OffchainResolver.sol";
export type { offchainResolverSol };
export type { Enumerator } from "./Enumerator";
export type { IERC721A } from "./IERC721A";
export type { IERC721AQueryable } from "./IERC721AQueryable";
export type { IExtendedResolver } from "./IExtendedResolver";
