/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FlickENS } from "./FlickENS";
export type { IExtendedResolverWithProof } from "./IExtendedResolverWithProof";
export type { ITokenURIGenerator } from "./ITokenURIGenerator";
