/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseRegistrarImplementation } from "./BaseRegistrarImplementation";
export type { IBaseRegistrar } from "./IBaseRegistrar";
