/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BaseRegistrarImplementation__factory } from "./BaseRegistrarImplementation__factory";
export { IBaseRegistrar__factory } from "./IBaseRegistrar__factory";
