import NextHead from "next/head";
import { useLocale } from "@0xflick/feature-locale";

export function Head() {
  const { t } = useLocale("common");
  return (
    <>
      <NextHead>
        <title>{t("title_home")}</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </NextHead>
    </>
  );
}
